//CART
export const REQUEST_GET_PRODUCTS_IN_CART = "REQUEST_GET_PRODUCTS_IN_CART";
export const GET_PRODUCTS_IN_CART_SUCCESS = "GET_PRODUCTS_IN_CART_SUCCESS";
export const GET_PRODUCTS_IN_CART_FAIL = "GET_PRODUCTS_IN_CART_FAIL";
export const REQUEST_EDIT_PRODUCT_IN_CART = "REQUEST_EDIT_PRODUCT_IN_CART";
export const EDIT_PRODUCT_IN_CART_SUCCESS = "EDIT_PRODUCT_IN_CART_SUCCESS";
export const EDIT_PRODUCT_IN_CART_FAIL = "EDIT_PRODUCT_IN_CART_FAIL";

//PRODUCT
export const REQUEST_GET_PRODUCT = "REQUEST_GET_PRODUCT";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
